### ISSUE TITLE
it not working

### ISSUE THREAD

**Issue by anoop-ananthan** [xabikos/vscode-jasmine#3]
This is nice tool which makes the test creation easy and love it.
`it` code is not working in VSCode. I'm using Ubuntu 14 & node 7.
Thanks

**Comment by alexthewilde** [comment]
Same here.

**Comment by alexthewilde** [comment]
It's actually working now.

**Comment by xabikos** [comment]
I will close this as there is no further feedback. But please let me know if there is an issue with the extension.

**Comment by andys8** [comment]
Hi @xabikos , it's currently not working for me. Either it's my mistake or there could be a problem depending on versions or interfering with other plugins? If it type for example `xit` and press `TAB`, nothing happens and there is the word `"xit"` followed by a tab. But it shows this suggestion:
![image](https://cloud.githubusercontent.com/assets/13085980/25281210/e56257e0-26ac-11e7-9439-5ef12208984f.png)

How can I support you to find a potential issue?

#### Versions
vscode-jasmine 0.2.1
vscode 1.11.2

**Comment by andys8** [comment]
There is actually a solution to fix the order: `editor.snippetSuggestions` :)
https://github.com/Microsoft/vscode/issues/9696
