### ISSUE TITLE
Snippets should not insert newlines

### ISSUE THREAD

**Issue by ajdaniel** [xabikos/vscode-jasmine#6]
I'm happy for this bug to be debated.

I'm using this module in Typescript files.

When I use these snippets, some insert a newline before and after. This usually causes my file to break lints because whitespace is usually inserted inside these newlines and violates [no-trailing-whitespace](https://palantir.github.io/tslint/rules/no-trailing-whitespace/).

Also, I think it's the user's choice as to the style of the code, whether there are newlines between statements or not.

**Comment by xabikos** [comment]
@ajdaniel thanks for mention this. 

I agree with you that adding a new line before and after the snippet is not the ideal situation. Is it fine by you to remove all the additional new lines both before and after the snippets?

**Comment by ajdaniel** [comment]
I will try and find some time to make a PR for you soon :)

**Comment by xabikos** [comment]
Solved by #7
